version: 2 # use CircleCI 2.0

app_test_steps: &app_test_steps
  - steps:
    - checkout # special step to check out source code to working directory

    - restore_cache: # special step to restore the dependency cache
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        keys: 
          - v1-repo-{{ checksum "package-lock.json" }}

    - run:
        name: Install dependencies with NPM
        command: npm install # replace with `yarn install` if using yarn

    - save_cache: # special step to save the dependency cache
        key: v1-repo-{{ checksum "package-lock.json" }}
        paths:
          - "node_modules"

    - run:
        name: Run tests
        command: npm test # replace with `yarn test` if using yarn

    - store_artifacts: 
        path: test-results.xml
        destination: tests2019
jobs:
  Node 10:
    docker: [{ image: "circleci/node:10"}]
    <<: *app_test_steps

workflows:
  version: 2
  Build and Test:
    jobs:
      - Node 10