version: 2 # use CircleCI 2.0

# install_npm: &install_npm
#   - run:
#       name: update-npm
#       command: 'sudo npm install -g npm@6'

app_test_steps: &app_test_steps
  - steps:
    # - *install_npm  
    - checkout # special step to check out source code to working directory
    - restore_cache: # special step to restore the dependency cache
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        keys: 
          - v1-repo-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v1-repo-{{ .Branch }
          - v1-repo-
    - run: npm --version
    - run:
        name: Install dependencies with NPM
        command: npm ci
    - run:
        name: Check current version of Node
        command: node -v          
    - save_cache: # special step to save the dependency cache
        key: v1-repo-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
          - "~/npm"
    - run:
        name: test
        command: npm test
    - store_artifacts: 
        path: test-results.xml
        destination: tests2019
jobs:
  Node 10:
    docker: [{ image: "circleci/node:10"}]
    <<: *app_test_steps

workflows:
  version: 2
  Build and Test:
    jobs:
      - Node 10