version: 2 # use CircleCI 2.0

install_npm: &install_npm
  - run:
      name: update-npm
      command: 'sudo npm install -g npm@6'

app_test_steps: &app_test_steps
  - steps:
    - *install_npm  
    - checkout # special step to check out source code to working directory
    - restore_cache: # special step to restore the dependency cache
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        keys: 
          - v1-repo-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v1-repo-{{ .Branch }
          - v1-repo-
    - run: npm --version
    - run:
        name: Install NPM
        command: npm ci
    - run:
        name: Check current version of Node
        command: node -v          
    - save_cache: # special step to save the dependency cache
        key: v1-repo-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
          - ~/npm
    - run: # run tests
        name: test
        command: npm test
      - store_artifacts: # special step to save test results as as artifact
        # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
        path: test-results.xml
        prefix: tests
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
        path: coverage
        prefix: coverage
    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: test-results.xml
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

jobs:
  Node 10:
    docker: [{ image: "circleci/node:10"}]
    <<: *app_test_steps
workflows:
  version: 2:
    Build and Test:
      jobs:
        - Node 10